//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileMVCShope.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int sale_id { get; set; }
        public Nullable<int> orderqty { get; set; }
        public Nullable<int> order_number { get; set; }
        public string order_name { get; set; }
        public Nullable<int> mobile_id { get; set; }
    
        public virtual mobile mobile { get; set; }
    }
}
