//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileMVCShope.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblMobile
    {
        [Display(Name ="Mobile Id")]
        public int Id { get; set; }
        public string Mobile { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
    }
}
